### ISSUE TITLE
明哥  请问divingintoipynb_pelican 在dongweiming.github.io中显示的原理是什么？

### ISSUE THREAD

**Issue by orangle** [dongweiming/divingintoipynb_pelican#1]
我通过[http://dongweiming.github.io/divingintoipynb_pelican/](http://dongweiming.github.io/divingintoipynb_pelican/) 访问到**divingintoipynb_pelican** 这个项目的在线演示。 但是在dongweiming.github.io中搜索**divingintoipynb**，并没有找到相关的源码页面。 所以我想问下怎么把一个项目的展示页放在 username.github.io/projectshow 上的？

**Comment by dongweiming** [comment]
你就要使用username这个用户创建一个项目叫做`projectshow`, 然后在这个项目的`settings`里面开启`GitHub Pages`. 我的dongweiming.github.io是github默认提供的一个功能,其实项目地址是`https://github.com/dongweiming/dongweiming.github.io` 他会帮我自动作为我的这个账号的主地址. 其他的都是子目录地址

**Comment by orangle** [comment]
懂了 这个是项目主页。 谢谢哈
